### ISSUE TITLE
Thank you very much :)

### ISSUE THREAD

**Issue by asigalov61** [bzamecnik/midi2audio#6]
Hey Bohumir,

Thank you very much for finally doing something about that nasty FluidSynth problem. Your efforts are much needed and appreciated.

I am already using it for my Music AI/SuperPiano repo implementation, although I prefer a simpler solution which you can find below:

```
!pip install pyFluidSynth
!apt install fluidsynth #Pip does not work for some reason. Only apt works
!pip install midi2audio

!cp /usr/share/sounds/sf2/FluidR3_GM.sf2 /content/font.sf2

from midi2audio import FluidSynth
from google.colab import output
from IPython.display import display, Javascript, HTML, Audio

FluidSynth("/content/font.sf2").midi_to_audio('output_midi.mid','output_wav.wav')
# set the src and play
Audio("output_wav.wav")
```

This way, it is a much more straightforward IMHO. But I still need midi2audio to summon FluidSynth properly. Our solutions are just a hack...I hope that FluidSynth team will do it right and properly eventually so that we do not have to go through all this pain 👍 

Thank you again.

Alex

**Comment by bzamecnik** [comment]
Hi Alex, glad to hear from you that the package is useful! 🙏🙇‍♂️
